# Generated by Django 4.1 on 2022-08-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_language_remove_course_language_course_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='name',
        ),
    ]
