# Generated by Django 4.1 on 2022-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('bio', models.TextField()),
                ('age', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to='teachers')),
            ],
        ),
    ]
