# Generated by Django 4.1 on 2022-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AddField(
            model_name='teachers',
            name='job_title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
