# Generated by Django 4.1 on 2022-09-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_teachers_options_teachers_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
