# Generated by Django 4.1 on 2022-09-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_teachers_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
