# Generated by Django 4.1 on 2022-09-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='git_hub',
            field=models.ImageField(default=1, upload_to='github/'),
            preserve_default=False,
        ),
    ]
