# Generated by Django 4.1 on 2022-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_teachers_git_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='languages',
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(max_length=255, to='courses.language'),
        ),
    ]
