# Generated by Django 4.1 on 2022-09-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_course_languages_course_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='languages',
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ForeignKey(default=1, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='courses.language'),
            preserve_default=False,
        ),
    ]
