# Generated by Django 4.1 on 2022-09-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_ratingstar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingStar',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='git_hub',
            field=models.ImageField(blank=True, null=True, upload_to='github/'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
