# Generated by Django 4.1 on 2022-09-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_human_jobpost_reguest'),
        ('courses', '0015_delete_ratingstar_alter_teachers_git_hub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='git_hub',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='job_title',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='settings.jobpost'),
        ),
    ]
