# Generated by Django 4.1 on 2022-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_teachers_git_hub_alter_teachers_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='job_title',
            field=models.CharField(max_length=150),
        ),
    ]
