# Generated by Django 4.1 on 2022-09-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_human_jobpost_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobpost',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pol',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
