# Generated by Django 4.1 on 2022-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_teachers_job_title'),
        ('settings', '0005_human_jobpost_reguest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguest',
            name='human',
        ),
        migrations.RemoveField(
            model_name='reguest',
            name='job_post',
        ),
        migrations.AddField(
            model_name='reguest',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reguest',
            name='subject',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
